language: python
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

python:
- 3.7
- 3.6

addons: 
  apt:
    packages: ffmpeg

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script: 
    - flake8
    - mypy . --ignore-missing-imports
    after_success:
    - pytest --cov --cov-config=setup.cfg
    - coveralls
  - os: osx
    language: sh
    before_install: brew install ffmpeg
    install: pip3 install -e .[tests]
  - os: windows
    language: sh
    before_install:
    - choco install ffmpeg
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

install: pip install -e .[tests]

script: pytest -rsv

